<center><h2>numpy</2></center>
<h4>np.array()</h4>
<h4>np.arange()</h4>

In [1]:
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [2]:
lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [3]:
%timeit [i**2 for i in lst]

723 ns ± 73.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [4]:
arr = np.array(lst)

In [5]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
%timeit np.array(lst)

894 ns ± 31.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [7]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [8]:
lst +[1]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1]

In [9]:
arr +[1]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
clear(lst)

In [11]:
l = [1, 5, 8, 9]
np_arr = np.array(l)

In [12]:
type(np_arr)

numpy.ndarray

In [13]:
np_arr.ndim

1

In [14]:
np_arr.shape

(4,)

In [15]:
clear(arr)

In [16]:
arr = np.arange(1, 11 ,2)

In [17]:
arr

array([1, 3, 5, 7, 9])

In [18]:
lst_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr_2d = np.array(lst_2d)

In [19]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
arr_2d.shape

(3, 3)

In [21]:
arr_2d.ndim

2

<center><h1>special array in numpy<?h1></center>
<h4>zeros()</h4>
<h4>ones()</h4>
<h4>diag()</h4>
<h4>identity()</h4>

In [22]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
np.diag((1, 2, 3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [25]:
np.identity((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
np.random.randint(1, 100)

42

In [27]:
arr = np.random.randint(1,20, (4, 4))
arr

array([[ 8,  3,  8, 18],
       [10,  9, 18,  9],
       [16,  3, 11,  8],
       [10,  5, 15, 11]])

In [28]:
arr.shape

(4, 4)

In [29]:
arr[0]

array([ 8,  3,  8, 18])

In [30]:
arr[-2]

array([16,  3, 11,  8])

In [31]:
arr[1, 2]

18

<h4>array slicing</h4>

In [32]:
arr[ : , 1]

array([3, 9, 3, 5])

In [33]:
arr[0, 0]=0

In [34]:
arr

array([[ 0,  3,  8, 18],
       [10,  9, 18,  9],
       [16,  3, 11,  8],
       [10,  5, 15, 11]])

In [35]:
mark = arr<10
arr[mark]


array([0, 3, 8, 9, 9, 3, 8, 5])

In [36]:
count = np.count_nonzero(mark)
count

8

In [37]:
mark

array([[ True,  True,  True, False],
       [False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False, False]])

In [38]:
a = np.array([10, 20, 30])
b = np.array([1, 5, 8])

In [39]:
a

array([10, 20, 30])

In [40]:
b

array([1, 5, 8])

In [41]:
a +b

array([11, 25, 38])

In [42]:
b**2
a -b


array([ 9, 15, 22])

In [43]:
a>20

array([False, False,  True])

In [44]:
np.log(a)

array([2.30258509, 2.99573227, 3.40119738])

In [45]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162])

In [46]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [47]:
A



array([[1, 2],
       [3, 4]])

In [48]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [ ]:
clear()0

In [ ]:
# Suppose arr is your NumPy matrix
padded_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(padded_arr)

In [50]:
a = np.arange(0, 24)

In [51]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [52]:
a = a.reshape(6, 4)

In [53]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [54]:
np.sqrt(a)

array([[0.        , 1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974, 2.64575131],
       [2.82842712, 3.        , 3.16227766, 3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335],
       [4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152]])

In [55]:
np.sum(a)

276

In [56]:
np.max(a)

23

In [57]:
np.min(a)

0

In [58]:
np.mean(a)

11.5

In [59]:
np.std(a)

6.922186552431729

In [60]:
np.sum(a , axis=0)

array([60, 66, 72, 78])

In [61]:
np.sum(a, axis=1)

array([ 6, 22, 38, 54, 70, 86])

In [63]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [66]:
a.reshape(4, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [74]:
a.T

array([[7, 6],
       [5, 8]])

In [83]:
clear()

In [84]:
A = np.random.randint(0 ,10, size=(3, 3))
a = np.random.randint(0, 10, size=(3, 3))

In [85]:
A

array([[0, 0, 3],
       [7, 4, 3],
       [4, 6, 8]])

In [87]:
a

array([[2, 8, 0],
       [5, 6, 4],
       [9, 3, 2]])

In [86]:
a+A

array([[ 2,  8,  3],
       [12, 10,  7],
       [13,  9, 10]])

In [89]:
A+4

array([[ 4,  4,  7],
       [11,  8,  7],
       [ 8, 10, 12]])

In [115]:
p1 = np.array([1, 2])
p2 = np.array([5, 5])

In [116]:
# Calculate the sum of squared differences between p2 and p1
s = 0
for i in range(2):
    s += (p2[i] - p1[i]) ** 2
print(s**0.5)

5.0


In [118]:
np.sqrt(np.sum((p2-p1)**2))

5.0

In [121]:
def distance(p1, p2):
	return np.sqrt(np.sum((p2 - p1) ** 2)) 

In [122]:
distance(p1, p2)

5.0

In [125]:
print(np.__version__)

1.26.4


In [137]:
# Create a new 2x2 array
new_arr = np.array([1, 2, 3, 4])
new_arr
np.reshape(new_arr, (2, 2))


array([[1, 2],
       [3, 4]])

In [139]:
padded_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print(padded_arr)

[[ 0  0  0  0  0  0]
 [ 0  0  3  8 18  0]
 [ 0 10  9 18  9  0]
 [ 0 16  3 11  8  0]
 [ 0 10  5 15 11  0]
 [ 0  0  0  0  0  0]]
