<center><h2>numpy</2></center>
<h4>np.array()</h4>
<h4>np.arange()</h4>

In [5]:
%pip install numpy
import numpy as np

Note: you may need to restart the kernel to use updated packages.


In [ ]:
lst = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

: 

: 

: 

In [ ]:
%timeit [i**2 for i in lst]

774 ns ± 82 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


: 

: 

In [ ]:
arr =np.array(lst)

: 

: 

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

: 

: 

In [ ]:
%timeit np.array(lst)

949 ns ± 29.3 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


: 

: 

In [ ]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

: 

: 

In [ ]:
lst +[1]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1]

: 

In [ ]:
arr +[1]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

: 

In [ ]:
clear(lst)

: 

In [ ]:
l = [1, 5, 8, 9]
np_arr = np.array(l)

: 

In [ ]:
type(np_arr)

numpy.ndarray

: 

In [ ]:
np_arr.ndim

1

: 

In [ ]:
np_arr.shape

(4,)

: 

In [ ]:
clear(arr)

: 

In [ ]:
arr = np.arange(1, 11 ,2)

: 

In [ ]:
arr

array([1, 3, 5, 7, 9])

: 

In [ ]:
lst_2d = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr_2d = np.array(lst_2d)

: 

In [ ]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

: 

In [ ]:
arr_2d.shape

(3, 3)

: 

In [ ]:
arr_2d.ndim

2

: 

<center><h1>special array in numpy<?h1></center>
<h4>zeros()</h4>
<h4>ones()</h4>
<h4>diag()</h4>
<h4>identity()</h4>

In [ ]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

: 

In [ ]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

: 

In [ ]:
np.diag((1, 2, 3))

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

: 

In [ ]:
np.identity((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

: 

In [ ]:
np.random.randint(1, 100)

38

: 

In [ ]:
arr = np.random.randint(1,20, (4, 4))
arr

array([[ 7, 12, 13,  2],
       [ 1,  4, 18,  1],
       [ 1,  9, 11, 11],
       [ 3, 14,  8, 18]])

: 

In [ ]:
arr.shape

(4, 4)

: 

In [ ]:
arr[0]

array([ 7, 12, 13,  2])

: 

In [ ]:
arr[-2]

NameError: name 'arr' is not defined

: 

: 

: 

: 

: 

: 

In [ ]:
d