In [1]:
!pip install pandas

In [2]:
import pandas as pd

In [3]:
book_titles = ["c++" , "java", "python", "javascript", "ruby"]

In [4]:
book_titles = pd.Series(book_titles)
book_titles

0           c++
1          java
2        python
3    javascript
4          ruby
dtype: object

In [5]:
type(book_titles)

pandas.core.series.Series

In [6]:
book_titles.index = [1, 2, 3, 4, 5]

In [7]:
book_titles [2]

'java'

In [8]:
import numpy as np


In [9]:
arr = np.random.randint(1, 100, size=(6, 4))
arr

array([[77,  1, 35, 73],
       [80, 85, 31, 52],
       [48, 68,  4, 73],
       [86, 93,  5, 56],
       [91, 75, 51, 66],
       [13,  2, 28, 36]])

In [10]:
df = pd.DataFrame(data=arr , columns=["A", "B", "C", "D"])
df

A   B   C   D
0  77   1  35  73
1  80  85  31  52
2  48  68   4  73
3  86  93   5  56
4  91  75  51  66
5  13   2  28  36

In [11]:
type(df)

pandas.core.frame.DataFrame

In [12]:
type(df["B"])

pandas.core.series.Series

In [13]:
cols = df.columns
cols

Index(['A', 'B', 'C', 'D'], dtype='object')

In [14]:
df['A+B'] = df['A'] + df['B']
df['A-B'] = df['A'] - df['B']	

In [15]:
df

A   B   C   D  A+B  A-B
0  77   1  35  73   78   76
1  80  85  31  52  165   -5
2  48  68   4  73  116  -20
3  86  93   5  56  179   -7
4  91  75  51  66  166   16
5  13   2  28  36   15   11

In [16]:
df.drop(columns=['A+B', 'A-B'], inplace=True)

In [17]:
df

A   B   C   D
0  77   1  35  73
1  80  85  31  52
2  48  68   4  73
3  86  93   5  56
4  91  75  51  66
5  13   2  28  36

In [18]:
df.index = "p q r s t u".split()
df

A   B   C   D
p  77   1  35  73
q  80  85  31  52
r  48  68   4  73
s  86  93   5  56
t  91  75  51  66
u  13   2  28  36

In [19]:
df.loc['p']

A    77
B     1
C    35
D    73
Name: p, dtype: int32

In [20]:
df.loc['t']

A    91
B    75
C    51
D    66
Name: t, dtype: int32

In [21]:
df.iloc[2:4, [0, 1]]

A   B
r  48  68
s  86  93

In [22]:
# Use iloc for integer-based slicing
df.iloc[-2:, -2:]

C   D
t  51  66
u  28  36

In [23]:
df

A   B   C   D
p  77   1  35  73
q  80  85  31  52
r  48  68   4  73
s  86  93   5  56
t  91  75  51  66
u  13   2  28  36

In [24]:
mask = df<30
mask

A      B      C      D
p  False   True  False  False
q  False  False  False  False
r  False  False   True  False
s  False  False   True  False
t  False  False  False  False
u   True   True   True  False

In [25]:
mark = df['B'] < 30
mark

p     True
q    False
r    False
s    False
t    False
u     True
Name: B, dtype: bool

In [26]:
# Select rows where column 'B' is less than 30, then show only columns 'C' and 'D'
result = df.loc[df['B'] < 30, ['C', 'D']]
result


C   D
p  35  73
u  28  36

In [27]:
df[mask]

A    B     C   D
p   NaN  1.0   NaN NaN
q   NaN  NaN   NaN NaN
r   NaN  NaN   4.0 NaN
s   NaN  NaN   5.0 NaN
t   NaN  NaN   NaN NaN
u  13.0  2.0  28.0 NaN

In [28]:
df['A'] > 50 

p     True
q     True
r    False
s     True
t     True
u    False
Name: A, dtype: bool

In [29]:
(df['A'] > 50) & (df['B'] < 50)

p     True
q    False
r    False
s    False
t    False
u    False
dtype: bool

In [30]:
df_array = df.to_numpy()
df_array

array([[77,  1, 35, 73],
       [80, 85, 31, 52],
       [48, 68,  4, 73],
       [86, 93,  5, 56],
       [91, 75, 51, 66],
       [13,  2, 28, 36]])

In [31]:
pd.read_csv("C:/Users/Kuvaladitya/Downloads/iris.csv")

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [32]:
iris = pd.read_csv("C:/Users/Kuvaladitya/Downloads/iris.csv")
iris.shape

(150, 5)

In [33]:
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [34]:
 iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [35]:
arr.ndim

2

In [36]:
iris.dtypes 

sepal_length    float64
sepal_width     float64
petal_length    float64
petal_width     float64
species          object
dtype: object

In [37]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [38]:
iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [39]:
mean = (iris['sepal_length'])
mean

0      5.1
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    6.7
146    6.3
147    6.5
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [40]:
iris['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [41]:
iris[iris['species'] == 'setosa'].shape

(50, 5)

In [42]:
iris[iris['species'] == 'versicolor'].shape

(50, 5)

In [43]:
iris['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [44]:
iris['sepal_length'].mean()

5.843333333333334

In [45]:
iris['sepal_length'].sum()

876.5

In [46]:
iris.sort_values(by='sepal_length')

sepal_length  sepal_width  petal_length  petal_width    species
13            4.3          3.0           1.1          0.1     setosa
42            4.4          3.2           1.3          0.2     setosa
38            4.4          3.0           1.3          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
41            4.5          2.3           1.3          0.3     setosa
..            ...          ...           ...          ...        ...
122           7.7          2.8           6.7          2.0  virginica
118           7.7          2.6           6.9          2.3  virginica
117           7.7          3.8           6.7          2.2  virginica
135           7.7          3.0           6.1          2.3  virginica
131           7.9          3.8           6.4          2.0  virginica

[150 rows x 5 columns]

In [47]:
len('setosa')

6

In [48]:
iris.apply(lambda x: x + x)

sepal_length  sepal_width  petal_length  petal_width             species
0            10.2          7.0           2.8          0.4        setosasetosa
1             9.8          6.0           2.8          0.4        setosasetosa
2             9.4          6.4           2.6          0.4        setosasetosa
3             9.2          6.2           3.0          0.4        setosasetosa
4            10.0          7.2           2.8          0.4        setosasetosa
..            ...          ...           ...          ...                 ...
145          13.4          6.0          10.4          4.6  virginicavirginica
146          12.6          5.0          10.0          3.8  virginicavirginica
147          13.0          6.0          10.4          4.0  virginicavirginica
148          12.4          6.8          10.8          4.6  virginicavirginica
149          11.8          6.0          10.2          3.6  virginicavirginica

[150 rows x 5 columns]

In [49]:
iris.aggregate('min')

sepal_length       4.3
sepal_width        2.0
petal_length       1.0
petal_width        0.1
species         setosa
dtype: object

In [50]:
iris.aggregate(['min', 'max'])

sepal_length  sepal_width  petal_length  petal_width    species
min           4.3          2.0           1.0          0.1     setosa
max           7.9          4.4           6.9          2.5  virginica

In [51]:
grouping = iris.groupby('species')

In [52]:
grouping.mean()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa             5.006        3.418         1.464        0.244
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

In [53]:
grouping.min()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa               4.3          2.3           1.0          0.1
versicolor           4.9          2.0           3.0          1.0
virginica            4.9          2.2           4.5          1.4

In [54]:
grouping.count()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa                50           50            50           50
versicolor            50           50            50           50
virginica             50           50            50           50

In [55]:
grouping.sum()

sepal_length  sepal_width  petal_length  petal_width
species                                                         
setosa             250.3        170.9          73.2         12.2
versicolor         296.8        138.5         213.0         66.3
virginica          329.4        148.7         277.6        101.3

In [56]:
grouping.describe().T

species                setosa  versicolor  virginica
sepal_length count  50.000000   50.000000  50.000000
             mean    5.006000    5.936000   6.588000
             std     0.352490    0.516171   0.635880
             min     4.300000    4.900000   4.900000
             25%     4.800000    5.600000   6.225000
             50%     5.000000    5.900000   6.500000
             75%     5.200000    6.300000   6.900000
             max     5.800000    7.000000   7.900000
sepal_width  count  50.000000   50.000000  50.000000
             mean    3.418000    2.770000   2.974000
             std     0.381024    0.313798   0.322497
             min     2.300000    2.000000   2.200000
             25%     3.125000    2.525000   2.800000
             50%     3.400000    2.800000   3.000000
             75%     3.675000    3.000000   3.175000
             max     4.400000    3.400000   3.800000
petal_length count  50.000000   50.000000  50.000000
             mean    1.464000    4.260000   5.552000
             std     0.173511    0.469911   0.551895
             min     1.000000    3.000000   4.500000
             25%     1.400000    4.000000   5.100000
             50%     1.500000    4.350000   5.550000
             75%     1.575000    4.600000   5.875000
             max     1.900000    5.100000   6.900000
petal_width  count  50.000000   50.000000  50.000000
             mean    0.244000    1.326000   2.026000
             std     0.107210    0.197753   0.274650
             min     0.100000    1.000000   1.400000
             25%     0.200000    1.200000   1.800000
             50%     0.200000    1.300000   2.000000
             75%     0.300000    1.500000   2.300000
             max     0.600000    1.800000   2.500000

### handling missing data
- dropna()
- fillna()

In [189]:
iris = pd.read_csv("C:/Users/Kuvaladitya/Downloads/iris.csv")

In [190]:
import warnings
warnings.filterwarnings("ignore")

In [191]:
iris

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [192]:
nan_index = np.random.randint(0, 150, size=20)
nan_index

array([ 94,  67, 117, 106, 147, 102,  44, 147,  70, 125,  52,   0, 145,
        83, 127,  50, 110, 104,  93,  20])

In [193]:
iris['sepal_length'][nan_index] = np.nan

In [194]:
iris['sepal_length']

0      NaN
1      4.9
2      4.7
3      4.6
4      5.0
      ... 
145    NaN
146    6.3
147    NaN
148    6.2
149    5.9
Name: sepal_length, Length: 150, dtype: float64

In [195]:
nan_index = np.random.randint(0, 150, size=15)
nan_index

array([ 14,  82,  58,  70, 101,  25, 139, 108,  85,  19,  48,  18,  62,
       131, 135])

In [196]:
iris['petal_length'][nan_index] = np.nan

In [197]:
iris['petal_length']

0      1.4
1      1.4
2      1.3
3      1.5
4      1.4
      ... 
145    5.2
146    5.0
147    5.2
148    5.4
149    5.1
Name: petal_length, Length: 150, dtype: float64

In [198]:
iris.isna().sum()

sepal_length    19
sepal_width      0
petal_length    15
petal_width      0
species          0
dtype: int64

In [ ]:
 iris['sepal_length'].fillna(iris['sepal_length'].mean(), inplace=True)

In [202]:
iris

sepal_length  sepal_width  petal_length  petal_width    species
0         5.79771          3.5           1.4          0.2     setosa
1         4.90000          3.0           1.4          0.2     setosa
2         4.70000          3.2           1.3          0.2     setosa
3         4.60000          3.1           1.5          0.2     setosa
4         5.00000          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145       5.79771          3.0           5.2          2.3  virginica
146       6.30000          2.5           5.0          1.9  virginica
147       5.79771          3.0           5.2          2.0  virginica
148       6.20000          3.4           5.4          2.3  virginica
149       5.90000          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

###  Concat/Merge Dataframes

In [218]:
new_pf = pd.DataFrame(np.random.randint(0,7 , size=(10, 4)))
new_pf

0  1  2  3
0  0  2  4  0
1  2  2  1  4
2  3  5  6  6
3  5  1  4  4
4  0  3  1  6
5  2  4  5  1
6  1  0  3  2
7  1  5  6  6
8  0  4  0  1
9  2  3  0  0

In [219]:
new_pf['species']  = 'new-species'

In [220]:
new_pf.head()

0  1  2  3      species
0  0  2  4  0  new-species
1  2  2  1  4  new-species
2  3  5  6  6  new-species
3  5  1  4  4  new-species
4  0  3  1  6  new-species

In [226]:
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [227]:
new_pf.columns = iris.columns

In [228]:
new_pf.head()

sepal_length  sepal_width  petal_length  petal_width      species
0             0            2             4            0  new-species
1             2            2             1            4  new-species
2             3            5             6            6  new-species
3             5            1             4            4  new-species
4             0            3             1            6  new-species

In [230]:
pd.concat([iris, new_pf], axis=0)

sepal_length  sepal_width  petal_length  petal_width      species
0        5.79771          3.5           1.4          0.2       setosa
1        4.90000          3.0           1.4          0.2       setosa
2        4.70000          3.2           1.3          0.2       setosa
3        4.60000          3.1           1.5          0.2       setosa
4        5.00000          3.6           1.4          0.2       setosa
..           ...          ...           ...          ...          ...
5        2.00000          4.0           5.0          1.0  new-species
6        1.00000          0.0           3.0          2.0  new-species
7        1.00000          5.0           6.0          6.0  new-species
8        0.00000          4.0           0.0          1.0  new-species
9        2.00000          3.0           0.0          0.0  new-species

[160 rows x 5 columns]

In [239]:
df1 = pd.DataFrame({
	'S_name': ['Monit', 'Jain', 'Pret', 'Monit', 'Jain', 'Pret'],
	'cgpa': [1, 2, 3, 5, 6, 7],
})
df1

sym_name  cgpa
0    Monit     1
1     Jain     2
2     Pret     3
3    Monit     5
4     Jain     6
5     Pret     7

In [244]:
df2 = pd.DataFrame({
	'T_name': ['Monit', 'Jain', 'Pret'],
	'cgpa': [4, 5, 6],})
df2

T_name  cgpa
0  Monit     4
1   Jain     5
2   Pret     6

In [248]:
df1.merge(df2, how = 'inner')

sym_name  cgpa T_name
0    Monit     5   Jain
1     Jain     6   Pret

In [250]:
df1.merge(df2, how = 'left')

sym_name  cgpa T_name
0    Monit     1    NaN
1     Jain     2    NaN
2     Pret     3    NaN
3    Monit     5   Jain
4     Jain     6   Pret
5     Pret     7    NaN

In [253]:
df.merge(df2, how = 'right')

MergeError: No common columns to perform merge on. Merge options: left_on=None, right_on=None, left_index=False, right_index=False

In [257]:
df1.merge(df2, how='outer', left_on='sym_name', right_on='T_name')

sym_name  cgpa_x T_name  cgpa_y
0     Jain       2   Jain       5
1     Jain       6   Jain       5
2    Monit       1  Monit       4
3    Monit       5  Monit       4
4     Pret       3   Pret       6
5     Pret       7   Pret       6

In [258]:
iris.isna().sum()

sepal_length     0
sepal_width      0
petal_length    15
petal_width      0
species          0
dtype: int64