In [3]:
!pip install pandas

In [4]:
import pandas as pd

In [5]:
book_titles = ["c++" , "java", "python", "javascript", "ruby"]

In [11]:
book_titles = pd.Series(book_titles)
book_titles

0           c++
1          java
2        python
3    javascript
4          ruby
dtype: object

In [ ]:
type(book_titles)

pandas.core.series.Series

In [13]:
book_titles.index = [1, 2, 3, 4, 5]

In [14]:
book_titles [2]

'java'

In [16]:
import numpy as np


In [34]:
arr = np.random.randint(1, 100, size=(6, 4))
arr

array([[10, 71, 62, 74],
       [50, 37, 79, 67],
       [52, 48, 11,  7],
       [35, 15, 29, 23],
       [53, 47, 76, 56],
       [86,  4, 84, 17]])

In [35]:
df = pd.DataFrame(data=arr , columns=["A", "B", "C", "D"])
df

A   B   C   D
0  10  71  62  74
1  50  37  79  67
2  52  48  11   7
3  35  15  29  23
4  53  47  76  56
5  86   4  84  17

In [36]:
type(df)

pandas.core.frame.DataFrame

In [39]:
type(df["B"])

pandas.core.series.Series

In [41]:
cols = df.columns
cols

Index(['A', 'B', 'C', 'D'], dtype='object')

In [49]:
df['A+B'] = df['A'] + df['B']
df['A-B'] = df['A'] - df['B']	

In [50]:
df

A   B   C   D  A+B  A-B
0  10  71  62  74   81  -61
1  50  37  79  67   87   13
2  52  48  11   7  100    4
3  35  15  29  23   50   20
4  53  47  76  56  100    6
5  86   4  84  17   90   82

In [51]:
df.drop(columns=['A+B', 'A-B'], inplace=True)

In [52]:
df

A   B   C   D
0  10  71  62  74
1  50  37  79  67
2  52  48  11   7
3  35  15  29  23
4  53  47  76  56
5  86   4  84  17

In [60]:
df.index = "p q r s t u".split()
df

A   B   C   D
p  10  71  62  74
q  50  37  79  67
r  52  48  11   7
s  35  15  29  23
t  53  47  76  56
u  86   4  84  17

In [61]:
df.loc['p']

A    10
B    71
C    62
D    74
Name: p, dtype: int32

In [62]:
df.loc['t']

A    53
B    47
C    76
D    56
Name: t, dtype: int32

In [69]:
df.iloc[2:4, [0, 1]]

A   B
r  52  48
s  35  15

In [76]:
# Use iloc for integer-based slicing
df.iloc[-2:, -2:]

C   D
t  76  56
u  84  17

In [77]:
df

A   B   C   D
p  10  71  62  74
q  50  37  79  67
r  52  48  11   7
s  35  15  29  23
t  53  47  76  56
u  86   4  84  17

In [79]:
mask = df<30
mask

A      B      C      D
p   True  False  False  False
q  False  False  False  False
r  False  False   True   True
s  False   True   True   True
t  False  False  False  False
u  False   True  False   True

In [83]:
mark = df['B'] < 30
mark

p    False
q    False
r    False
s     True
t    False
u     True
Name: B, dtype: bool

In [86]:
# Select rows where column 'B' is less than 30, then show only columns 'C' and 'D'
result = df.loc[df['B'] < 30, ['C', 'D']]
result


C   D
s  29  23
u  84  17

In [87]:
df[mask]

A     B     C     D
p  10.0   NaN   NaN   NaN
q   NaN   NaN   NaN   NaN
r   NaN   NaN  11.0   7.0
s   NaN  15.0  29.0  23.0
t   NaN   NaN   NaN   NaN
u   NaN   4.0   NaN  17.0

In [94]:
df['A'] > 50 

p    False
q    False
r     True
s    False
t     True
u     True
Name: A, dtype: bool

In [97]:
(df['A'] > 50) & (df['B'] < 50)

p    False
q    False
r     True
s    False
t     True
u     True
dtype: bool

In [99]:
df_array = df.to_numpy()
df_array

array([[10, 71, 62, 74],
       [50, 37, 79, 67],
       [52, 48, 11,  7],
       [35, 15, 29, 23],
       [53, 47, 76, 56],
       [86,  4, 84, 17]])

In [113]:
pd.read_csv("C:/Users/Kuvaladitya/Downloads/iris.csv")

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [117]:
iris = pd.read_csv("C:/Users/Kuvaladitya/Downloads/iris.csv")
iris.shape

(150, 5)

In [118]:
iris.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [119]:
 iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [126]:
arr.ndim

2

array([[ 20, 142, 124, 148],
       [100,  74, 158, 134],
       [104,  96,  22,  14],
       [ 70,  30,  58,  46],
       [106,  94, 152, 112],
       [172,   8, 168,  34]])